// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	logging "cloud.google.com/go/logging"
	mock "github.com/stretchr/testify/mock"
)

// CloudLogger is an autogenerated mock type for the CloudLogger type
type CloudLogger struct {
	mock.Mock
}

// Flush provides a mock function with no fields
func (_m *CloudLogger) Flush() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Flush")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Log provides a mock function with given fields: e
func (_m *CloudLogger) Log(e logging.Entry) {
	_m.Called(e)
}

// NewCloudLogger creates a new instance of CloudLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCloudLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *CloudLogger {
	mock := &CloudLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
